spring.application.name=ticketing

spring.datasource.url=jdbc:mariadb://localhost:3306/ticketing
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123
jwt.secret=thisIsAVeryLongSecretKeyThatShouldBeAtLeast256BitsLong1234567890
jwt.expiration=1200000

jwt.secret=yourSuperSecretKeyThatIsLongEnough1234567890
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.error.include-message=always